### PR TITLE
valid html

### PR DESCRIPTION
**Pull request by peterbe**

### CODE REVIEW

**Comment by freshp86** [comment]
Thanks for the pull request. Could you sign the contributor agreement as described at https://github.com/google/lovefield/blob/master/CONTRIBUTING.md?

**Comment by peterbe** [comment]
I did that. Under the github username `peterbe` but I think under a different email address than the one I have on GitHub.

**Comment by freshp86** [comment]
Thanks, I see it now. Will be merging this pull request shortly.

**Comment by freshp86** [comment]
Merged as https://github.com/google/lovefield/commit/0276ec8934626862c87b35dee9bebccfbf94521a.

**Pull request closed without merging**
