### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by freshp86** [comment]
So, after the long wait, we are finally ready to accept external contribution. Would you mind updating the pull request to resolve conflicts?

**Comment by pborreli** [comment]
@freshp86 done, thx :hatching_chick:

**Comment by freshp86** [comment]
Thanks! Will be merging this first thing next week (Tuesday).

**Comment by freshp86** [comment]
We would also like to give credit to each contributor. Could you also update the https://github.com/google/lovefield/blob/master/AUTHORS file, by adding your name and email?

**Comment by pborreli** [comment]
@freshp86 done :shipit:

**Comment by pborreli** [comment]
very glad it finally happens during my short time on earth, thank you :pray:

**Pull request merged**
