### PR TITLE
Fix incompatibility issues with systemjs and jspm

### PR DESCRIPTION
**Pull request by digital-synapse**
This fix allows loading lovefield asynchronously via systemjs to work as expected using the standard import syntax.

import 'lovefield';   // lf object is now available to this module.

### CODE REVIEW

**Comment by freshp86** [comment]
lovefield.js and lovefield.min.js are auto-generated every time we export (from Google's internal repository to Github). This means that even if we patch this now, the next time we export (which we do every 1-2 days), it will be overwritten again, and will be missing the newly added line at the end.

So we have to change are automated export script to add those lines, such that they exist when exporting. Will take a look at it, and update this thread accordingly.

**Comment by freshp86** [comment]
I just realized that this change also removes the fix for WebWorkers that had been committed at https://github.com/google/lovefield/commit/624e553ed00f68330949ff9cbff356deefd71c3d.

Need to find a way to support both webworkers and exporting lovefield as a module. Not sure if this is possible in one JS binary. Needs investigation.

**Comment by digital-synapse** [comment]
would something like this work?

var window = (window.document === undefined)  ? this : window;

**Comment by digital-synapse** [comment]
this seems to fix the issue.
var window = window===undefined ? this : window;

heres the plunk: http://plnkr.co/edit/bJ8eioZA3mfIyyREQsgD?p=preview

**Comment by freshp86** [comment]
Thanks for the pull request. As explained at https://github.com/google/lovefield/pull/91#issuecomment-143270632, those files are auto-generated, so accepting this pull request will not have a lasting effect. I have the proper fix which should be coming very soon, will update this thread.

**Comment by freshp86** [comment]
I believe that https://github.com/google/lovefield/commit/599f5d9b8bb9fc37fa4acf7b8cf3593ae7ef3191, should have fixed the issue. Can you give it a try?

**Comment by digital-synapse** [comment]
Okay thanks I'll check it out

**Comment by digital-synapse** [comment]
I have confirmed that this 599f5d9 is working for jspm/systemjs async module loading.

**Pull request closed without merging**
