### PR TITLE
Added material Design

### PR DESCRIPTION
**Pull request by nicolabortignon**
- Integrated material design light
- added responsiveness behavior for cross screen support
- added analytics
- minor updates to the logo
- updated date in footer (now is dynamically generated)

### CODE REVIEW

**Comment by freshp86** [comment]
Can we remove analytics? Github already provides a lot of statistics about a project's traffic at https://github.com/google/lovefield/graphs/traffic. I don't see any benefit of adding (and maintaining) our own stats.

**Comment by nicolabortignon** [comment]
Done. commit 8eac6edf0e8e320f5edf69bf223ff025d55980c9

**Comment by freshp86** [comment]
Looks very nice! Thanks. Just a few comments.

1. The bottom right "Google Inc 2015" is a broken link now. I don't think it should be a link at all, just plain text.
2. Can we add back the link to Lovefield's forum? It is the 2nd from he bottom left on the old UI.

**Comment by nicolabortignon** [comment]
1. Fixed with 1bcbd49dbd5e2896fcf1b98bb47f9b2863c95f02
2. Added back with 1bcbd49dbd5e2896fcf1b98bb47f9b2863c95f02

**Pull request merged**
